### PR TITLE
ADMIN: ATTRIBUTES: bug fix, entityless attributes paginator

### LINKED ISSUE #116: Entityless attribute keys pagination
* When editing an attribute definition, the pagination on the page with keys is not working.

### PR DESCRIPTION
**Pull request by DanoFecko**
resolves #116

### CODE REVIEW

File: apps/admin-gui/src/app/shared/components/entityless-attribute-keys-list/entityless-attribute-keys-list.component.ts [hunk 1]
```diff
@@ -121,11 +120,13 @@ export class EntitylessAttributeKeysListComponent implements OnChanges, OnInit {
...
     this.records.push(rec);
-    this.ngOnChanges(undefined);
+    this.dataSource.data = this.records;
+    this.setDataSource();
     this.selection.clear();
     this.selection.select(rec);
     this.isAddButtonDisabled = true;
-    this.paginator.lastPage();
+    // .lastPage() has to be delayed, otherwise it wont go to last page if number of records modulo page size is 1
+    setTimeout(() => this.paginator.lastPage(), 100);
```
Comment (Vojtech-Sassmann) [inline apps/admin-gui/src/app/shared/components/entityless-attribute-keys-list/entityless-attribute-keys-list.component.ts]: I think it makes sense to add the new record to the start of the list. Also, I am a little worried about this solution which is using the timeout.

**Comment by DanoFecko** [comment]
I wish i knew what was the problem. I usually it only takes to change OnInit to AfterViewInit when paginator is broken, but here it didn't work. So i tried everything, untill this worked.

File: apps/admin-gui/src/app/shared/components/entityless-attribute-keys-list/entityless-attribute-keys-list.component.ts (hunk 1 above)
Comment (DanoFecko) [reply apps/admin-gui/src/app/shared/components/entityless-attribute-keys-list/entityless-attribute-keys-list.component.ts]: Done, there's no timeout anymore, and added attribute is on top (although after save backend puts him at the end)
